name: CI

on:
  push:
  pull_request:
    branches:
    - master

jobs:
  test:
    strategy:
      matrix:
        ocaml-version:
        - '4.03'
        - '4.04'
        - '4.05'
        - '4.06'
        - '4.07'
        - '4.08'
        - '4.09'
        - '4.10'
        - '4.11'
    runs-on: ubuntu-latest
    env:
      OCAML_VERSION: ${{ matrix.ocaml-version }}
    steps:
    - uses: actions/checkout@v2
    - name: Use OCaml ${{ matrix.ocaml-version }}
      uses: avsm/setup-ocaml@v1
      with:
        ocaml-version: ${{ matrix.ocaml-version }}
    - name: Install dependencies
      run: |
        opam install . --deps-only --with-doc --with-test
    - name: Build
      run: |
        opam exec -- dune build
    - name: Test
      run: |
        opam exec -- dune runtest
